name: Build Documentation with Sphinx
description: Builds documentation using Sphinx and uploads it as an artifact.

runs:
  using: composite
  steps:
    - name: Build docs
      run: |
        uv run sphinx-build -M clean docs/source/ docs/build/
        uv run sphinx-build -M html docs/source/ docs/build/
        echo "✅ Documentation built successfully"
      shell: bash

    - name: Upload docs artifact
      uses: actions/upload-artifact@v7
      with:
        name: documentation
        path: docs/build/
