name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-pyproject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/ci/validate-pyproject@main

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/ci/ruff@main

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/ci/mypy@main

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/setup/check-tests-exists@main
        id: check-tests-exists
      - uses: ./actions/ci/pytest@main
        if: steps.check-tests-exists.outputs.exists == 'true'

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/ci/bandit@main

  pip-audit:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/ci/pip-audit@main

  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/setup/check-frontend-exists@main
        id: check-frontend-exists

      - uses: ./actions/ci/version-check@main
        with:
          frontend-dir-exists: ${{ steps.check-frontend-exists.outputs.exists }}

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/setup/check-frontend-exists@main
        id: check-frontend-exists

      - uses: ./actions/ci/frontend@main
        if: steps.check-frontend-exists.outputs.exists == 'true'
