name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  python-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/setup/setup-uv-python
      - uses: ./actions/setup/install-python-dev
      - uses: ./actions/setup/check-frontend-exists
        id: check-frontend-exists

      - uses: ./actions/ci/python-validate
        with:
          frontend-dir-exists: ${{ steps.check-frontend-exists.outputs.exists }}

  python-code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/setup/setup-uv-python
      - uses: ./actions/setup/install-python-dev
      - uses: ./actions/ci/python-code-check

  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/setup/setup-uv-python
      - uses: ./actions/setup/install-python-dev

      - uses: ./actions/setup/check-tests-exists
        id: check-tests-exists

      - uses: ./actions/ci/python-tests
        if: steps.check-tests-exists.outputs.exists == 'true'

  python-security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/setup/setup-uv-python
      - uses: ./actions/setup/install-python-dev
      - uses: ./actions/ci/python-security-check

  npm-code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/setup/setup-node

      - uses: ./actions/setup/check-frontend-exists
        id: check-frontend-exists

      - uses: ./actions/ci/npm-code-check
        if: steps.check-frontend-exists.outputs.exists == 'true'

  npm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/setup/setup-node

      - uses: ./actions/setup/check-frontend-exists
        id: check-frontend-exists

      - uses: ./actions/ci/npm-tests
        if: steps.check-frontend-exists.outputs.exists == 'true'
