name: Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/setup/setup-uv-python
      - uses: ./actions/setup/install-python-docs
      - uses: ./actions/docs/build-docs

  publish-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: ./actions/docs/publish-docs
        id: publish
